# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.6.0'
    checkLatest: true
- script: nuget restore
  displayName: 'Restore packages'
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '$(Build.SourcesDirectory)/TreeWalk/*.*'
    versioningScheme: 'off'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    ArtifactName: 'NuGetPackage'
    publishLocation: 'Container'
