# This is a basic workflow to help you get started with Actions

name: NugetPublish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: NuGet/setup-nuget@v1.0.5
        with:          
          nuget-api-key:  ${{ secrets.NUGET_KEY }}
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2.10.0
        with:
          workflow: main.yml
          name: TreeWalk.Nuget      
          branch: master          
      - name: Publish 
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: 'nuget push -ApiKey $env:NUGET_KEY -Source https://api.nuget.org/v3/index.json TreeWalk*.nupkg '
